In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('data/Social_Network_Ads.csv',index_col=0)
df.head()

          Gender   Age  EstimatedSalary  Purchased
User ID
15624510    Male  19.0          19000.0        0.0
15810944    Male  35.0          20000.0        0.0
15668575  Female  26.0          43000.0        0.0
15603246  Female  27.0          57000.0        0.0
15804002    Male  19.0          76000.0        0.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 400 entries, 15624510 to 15594041
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              398 non-null    float64
 2   EstimatedSalary  398 non-null    float64
 3   Purchased        398 non-null    float64
dtypes: float64(3), object(1)
memory usage: 15.6+ KB

In [4]:
df.describe()

              Age  EstimatedSalary   Purchased
count  398.000000       398.000000  398.000000
mean    37.711055     69577.889447    0.359296
std     10.477729     34080.549326    0.480398
min     18.000000     15000.000000    0.000000
25%     30.000000     43000.000000    0.000000
50%     37.000000     69500.000000    0.000000
75%     46.000000     87750.000000    1.000000
max     60.000000    150000.000000    1.000000

In [5]:
df.shape

(400, 4)

In [6]:
df['Gender'].value_counts()

Gender
Female    204
Male      196
Name: count, dtype: int64

In [7]:
df.groupby(['Gender', 'Purchased']).size()

Gender  Purchased
Female  0.0          126
        1.0           77
Male    0.0          129
        1.0           66
dtype: int64

In [8]:
df.isnull().sum()

Gender             0
Age                2
EstimatedSalary    2
Purchased          2
dtype: int64

In [9]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [10]:
df['EstimatedSalary']=df['EstimatedSalary'].fillna(df['EstimatedSalary'].mean())

In [11]:
df['Purchased']=df['Purchased'].fillna(df['Purchased'].mean())

In [12]:
df.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [13]:
X = df.drop(columns=['Purchased'])
y = df['Purchased']

In [14]:
# writing the df to a csv file
df.to_csv('data/Social_Network_Ads_cleaned.csv')

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
labelencoder = LabelEncoder()
X_train['Gender']  = labelencoder.fit_transform(X_train['Gender'])
X_test['Gender'] = labelencoder.transform(X_test['Gender'])

In [17]:
X_test

          Gender   Age  EstimatedSalary
User ID
15697424       0  46.0          22000.0
15609669       0  59.0          88000.0
15776733       0  28.0          44000.0
15724536       0  48.0          96000.0
15699284       0  29.0          28000.0
...          ...   ...              ...
15638003       0  35.0          50000.0
15685346       1  56.0         133000.0
15624755       0  54.0          26000.0
15609653       0  35.0          47000.0
15713912       0  37.0          78000.0

[80 rows x 3 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 400 entries, 15624510 to 15594041
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    float64
 2   EstimatedSalary  400 non-null    float64
 3   Purchased        400 non-null    float64
dtypes: float64(3), object(1)
memory usage: 15.6+ KB

In [19]:
scaler= StandardScaler()

In [20]:
scaler

StandardScaler()

In [21]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
clf = KNeighborsClassifier()

In [23]:
clf

KNeighborsClassifier()

In [24]:
# lets fit clf
clf.fit(X_train,y_train)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.