In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('data/Social_Network_Ads.csv', index_col=0)
df

          Gender   Age  EstimatedSalary  Purchased
User ID
15624510    Male  19.0          19000.0        0.0
15810944    Male  35.0          20000.0        0.0
15668575  Female  26.0          43000.0        0.0
15603246  Female  27.0          57000.0        0.0
15804002    Male  19.0          76000.0        0.0
...          ...   ...              ...        ...
15691863  Female  46.0          41000.0        1.0
15706071    Male  51.0          23000.0        1.0
15654296  Female  50.0          20000.0        1.0
15755018    Male  36.0          33000.0        0.0
15594041  Female  49.0          36000.0        1.0

[400 rows x 4 columns]

In [10]:
df.head()

          Gender   Age  EstimatedSalary  Purchased
User ID
15624510    Male  19.0          19000.0        0.0
15810944    Male  35.0          20000.0        0.0
15668575  Female  26.0          43000.0        0.0
15603246  Female  27.0          57000.0        0.0
15804002    Male  19.0          76000.0        0.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 400 entries, 15624510 to 15594041
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              398 non-null    float64
 2   EstimatedSalary  398 non-null    float64
 3   Purchased        398 non-null    float64
dtypes: float64(3), object(1)
memory usage: 15.6+ KB

In [12]:
df.nunique()

Gender               2
Age                 43
EstimatedSalary    116
Purchased            2
dtype: int64

In [13]:
df['Age'].unique()

array([19., 35., 26., 27., 32., 25., 20., 18., 29., 47., 45., 46., 48.,
       49., 31., 21., 28., 33., 30., 23., 24., nan, 22., 59., 34., 39.,
       38., 37., 42., 40., 36., 41., 58., 55., 52., 60., 56., 53., 50.,
       51., 57., 44., 43., 54.])

In [14]:
df.shape

(400, 4)

In [16]:
df['Gender'].value_counts()

Gender
Female    204
Male      196
Name: count, dtype: int64

In [19]:

df.groupby(['Gender', 'Purchased']).size()

Gender  Purchased
Female  0.0          126
        1.0           77
Male    0.0          129
        1.0           66
dtype: int64