In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('data/employee data.xlsx')
df.head()

,Employee,Location,Sex,Salary,Date Hired,Exempt,Unnamed: 6,Unnamed: 7
0,Krista Orcutt,Pennsylvania,Female,54176,1991-10-22,False,NaN,NaN
1,Cora Soto,Massachusetts,Female,58120,1992-01-15,True,NaN,NaN
2,James Millen,Washington,Male,26135,1992-05-25,False,NaN,NaN
3,Tara Applewhite,California,Female,80274,1992-05-30,True,NaN,NaN
4,Devin Lear,Massachusetts,Male,43532,1992-06-29,False,NaN,NaN

In [3]:
df.drop(columns=['Unnamed: 6', 'Unnamed: 7'], inplace=True)
df.head()

          Employee       Location     Sex  Salary Date Hired  Exempt
0    Krista Orcutt   Pennsylvania  Female   54176 1991-10-22   False
1        Cora Soto  Massachusetts  Female   58120 1992-01-15    True
2     James Millen     Washington    Male   26135 1992-05-25   False
3  Tara Applewhite     California  Female   80274 1992-05-30    True
4       Devin Lear  Massachusetts    Male   43532 1992-06-29   False

In [4]:
df['Location'].value_counts()

Location
California       108
New York          91
Massachusetts     90
Pennsylvania      46
Washington        45
Arizona           20
Name: count, dtype: int64

In [5]:
gender_location_counts = df.groupby(['Location', 'Sex']).size()
gender_location_counts

Location       Sex
Arizona        Female     5
               Male      15
California     Female    44
               Male      64
Massachusetts  Female    43
               Male      47
New York       Female    51
               Male      40
Pennsylvania   Female    17
               Male      29
Washington     Female    16
               Male      29
dtype: int64

In [6]:
num_people = df.query("Location == 'Massachusetts' and Salary > 58000").shape[0]
print(num_people)

27

In [7]:
df.query("Location == 'Massachusetts' and (Sex=='Female' or Salary > 50000)")

            Employee       Location     Sex  Salary Date Hired  Exempt
1          Cora Soto  Massachusetts  Female   58120 1992-01-15    True
7        Terry Gross  Massachusetts    Male   64497 1992-09-19    True
17      Kimberly Vos  Massachusetts  Female   57568 1993-03-18    True
20     Richard Guard  Massachusetts    Male   60587 1993-05-28    True
28       PhyllisTodd  Massachusetts  Female   23142 1993-10-24   False
..               ...            ...     ...     ...        ...     ...
352    Joan Morrison  Massachusetts  Female   83972 2010-07-31    True
360       Irving Kim  Massachusetts    Male   51647 2010-12-12   False
367       Brian Bass  Massachusetts    Male   66145 2011-03-25    True
381  Filomena Jordan  Massachusetts  Female   48789 2011-12-14   False
397     Joseph Ramos  Massachusetts    Male   52303 2012-07-18   False

[62 rows x 6 columns]

In [8]:
df1 = pd.read_json('data/iris.json')
df1

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list"
df2 = pd.read_html(url)

In [10]:
df2[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523

In [11]:
url = "https://www.sbp.org.pk/careers/status.asp"
tables = pd.read_html(url)
print("Number of tables found:", len(tables))
tables[12]

Number of tables found: 15

,0,1,2,3,4
0,S.No.,Positions,Advertisement,Application Closing Date,Status
1,1,Banking Policy & Regulations Department,Click Here,"June 16, 2025",Written Test has been conducted.
2,2,Cyber Risk Management Department,Click Here,"June 16, 2025",The result has been updated on the NTS website.
3,3,Cyber Security Department,Click Here,"February 17, 2025",Recruitment drive has been completed.
4,4,"Museum, Art Gallery & Archives Department",Click Here,"January 6, 2025",Recruitment drive has been completed.
5,5,Monetary Policy Department,Click Here,"December 9th , 2024",Recruitment drive has been completed.
6,6,Contractual positions in External Communicatio...,Click Here,"October 21, 2024",Recruitment drive has been completed.
7,7,Assistant Director (OG-2) - Archives,Click Here,"October 21, 2024",Recruitment drive has been completed.
8,8,Economic Policy Review Department,Click Here,"September 23, 2024",Recruitment drive has been completed.
9,9,Research Department,Click Here,"September 23, 2024",Recruitment drive has been closed.
10,10,Additional Director (OG-6),Click Here,"Aug 12, 2024",Recruitment drive has been closed.
11,11,Information Technology Group,Click Here,"Jul 22, 2024",Recruitment drive has been completed.
12,12,Human Resource Department,Click Here,"June 10, 2024",Recruitment drive has been completed.
13,13,SBP Memorial Chairs in Economics,Click Here,NaN,Application submission in process
14,NaN,NaN,NaN,NaN,NaN

In [12]:
import sqlite3

In [18]:
conn = sqlite3.connect('data/chinook.db')
conn

In [14]:
# conn = sqlite3.connect('Chinook_Sqlite.sqlite')
# conn

In [19]:
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type ='table';", conn)
# album = pd.read_sql("SELECT * FROM Album;", conn)
tables

Empty DataFrame
Columns: [name]
Index: []