In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

In [5]:
df = pd.read_csv('data/multiple_linear_regression_dataset.csv')

In [6]:
df.head()

   area  bedrooms  age   price
0  3774         1   26  175023
1  1460         5   27  117324
2  1894         3   28  111840
3  1730         1    8   44561
4  1695         3    2  118099

In [7]:
df.tail()

     area  bedrooms  age   price
795  2694         5   23  138642
796  1856         2   16   85965
797  3976         3    9  233271
798  2149         1   28  108608
799  1766         3    9  119221

In [8]:
df.describe()

             area    bedrooms         age          price
count   800.00000  800.000000  800.000000     800.000000
mean   2342.89375    2.947500   14.382500  135028.830000
std     972.78049    1.436079    8.650563   53923.976963
min     601.00000    1.000000    0.000000    -314.000000
25%    1553.75000    2.000000    7.000000   93519.250000
50%    2286.50000    3.000000   14.000000  134974.000000
75%    3213.75000    4.000000   22.000000  173372.250000
max    3998.00000    5.000000   29.000000  273153.000000

In [9]:
df.describe

<bound method NDFrame.describe of      area  bedrooms  age   price
0    3774         1   26  175023
1    1460         5   27  117324
2    1894         3   28  111840
3    1730         1    8   44561
4    1695         3    2  118099
..    ...       ...  ...     ...
795  2694         5   23  138642
796  1856         2   16   85965
797  3976         3    9  233271
798  2149         1   28  108608
799  1766         3    9  119221

[800 rows x 4 columns]>

In [ ]:
df['bedrooms'].nunique() # Number of unique values in 'bedrooms' column

5

In [12]:
df['bedrooms'].unique() # Unique values in 'bedrooms' column

array([1, 5, 3, 4, 2], dtype=int64)

In [13]:
df['bedrooms'].value_counts() # Count of unique values in 'bedrooms' column

bedrooms
1    172
5    166
3    164
2    164
4    134
Name: count, dtype: int64

In [14]:
df.isnull().sum() # Check for missing values in the dataset

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [16]:
X = df.drop(columns=['price'])
y = df['price']

In [17]:
X

     area  bedrooms  age
0    3774         1   26
1    1460         5   27
2    1894         3   28
3    1730         1    8
4    1695         3    2
..    ...       ...  ...
795  2694         5   23
796  1856         2   16
797  3976         3    9
798  2149         1   28
799  1766         3    9

[800 rows x 3 columns]

In [18]:
y

0      175023
1      117324
2      111840
3       44561
4      118099
        ...
795    138642
796     85965
797    233271
798    108608
799    119221
Name: price, Length: 800, dtype: int64

In [19]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
X_train

     area  bedrooms  age
264  2530         4   20
615  3374         3   22
329  1227         2    1
342  2484         5    8
394  3843         5    5
..    ...       ...  ...
71    634         2    5
106  3712         2   12
270   786         5   12
435  3137         4   20
102  1363         3    7

[640 rows x 3 columns]

In [21]:
X_test

     area  bedrooms  age
696  3045         1    0
667  2235         2    5
63   3545         1   12
533  1496         5    4
66   1990         3   24
..    ...       ...  ...
589  2905         2   11
798  2149         1   28
744  3092         4   22
513  1681         5   28
670  3904         2    1

[160 rows x 3 columns]

In [25]:
len(X_train), len(X_test)

(640, 160)

In [22]:
reg = LinearRegression()

In [23]:
reg.fit(X_train, y_train)

LinearRegression()

In [24]:
reg.predict(X_test)

array([163363.31731031, 128659.06241562, 177992.78768485, 121116.49415549,
       110119.90898493, 108843.21732191,  87769.06352839, 171559.71749843,
        85255.88666275,  69615.99530256, 175655.53862739, 127066.57377564,
       199907.54568837, 211535.09060363, 185942.86177627,  99372.26021463,
       151108.42343995, 206814.48223421, 225408.88300905,  69389.72384715,
       174178.53394436, 116533.24182911, 189272.61192194, 187614.08005288,
       134847.94124921, 181085.31184066, 165587.9244417 , 158501.22956573,
        93340.02330666, 165419.01058541,  47956.13896508, 170332.46656327,
       208460.7421726 , 213570.02195042, 117103.44042353,  99477.03385836,
       171498.87077643, 101625.18025761, 100844.56843917, 189307.09733778,
       135564.88880367, 126825.76148507, 113949.41084761, 132154.1887058 ,
       150252.82693511,  63513.92162637, 135077.25036782, 183927.87501016,
       120296.99327286, 226428.69691169, 164146.51533229,  60649.48637077,
       187330.84098634,  74678.10325699, 210064.55123499,  77259.95814416,
       149066.52673019, 119485.93379896, 159031.13612804,  45167.79855366,
        82712.5549518 , 110938.75116945,  94604.23580058,  59511.26090859,
       111881.60429136, 148571.10558372, 227990.73789622, 180534.30195098,
       137852.95296061,  57225.96570472,  82868.98963898, 138751.63493954,
       164285.03012204, 100339.96161415, 107122.52133463, 128836.25903112,
       213321.42694923, 191824.97066192, 153402.00140301, 118671.12937482,
       167736.52230062,  46895.82579189, 140775.35592452,  72448.00680837,
       143282.06747577,  82412.4575567 , 176750.94732562, 166583.09730516,
       136137.40489149, 187901.69827887, 177004.08013577, 114766.48417623,
       117860.56994951,  66971.47624858, 110857.09393023,  39367.63971739,
       102095.35025571,  76101.1779921 ,  91862.35992552, 131796.73371158,
        95156.80730772, 119336.91593443,  48759.57437789,  96253.58199109,
       184294.67433246, 138258.48269756, 143440.47825728, 125419.20367946,
        96379.72767234,  86157.28900584,  56201.61399311, 129241.78876807,
       113417.89407893,  56918.90294664, 211042.75570929, 173110.59671007,
       169576.33713448,  60717.50569419, 125870.88065373, 161527.2960156 ,
       211761.81351871,  83475.1982839 , 106268.98649583, 127575.63283791,
       122461.6566016 ,  81122.54245474,  89910.69602433,  49558.67922017,
       159361.97398875, 163328.3804348 , 137367.58342924, 174908.75352667,
        98067.59703907, 208819.62462364,  40073.42549896, 127594.26002237,
       127874.41283679, 190541.67952387, 107626.67669997,  59923.91465804,
        86397.94264688, 203536.23448245, 206828.41296017,  62465.27027465,
       168628.58031564,  82083.68136204, 150471.9257891 , 125620.17539758,
       150846.34917248, 111380.53517814, 155248.23296235, 102064.40255166,
        94023.93700214,  86629.52066998, 188719.22306717, 156651.86316536,
        95946.47064409, 175375.99592216, 110250.14101548, 214158.84772929])

In [26]:
y_pred = reg.predict(X_test)

In [27]:
pd.DataFrame({'y_test': y_test, 'y_pred': y_pred, 'MAE': mean_absolute_error(y_test, y_pred),
              'MSE': mean_squared_error(y_test, y_pred), 'R2': r2_score(y_test, y_pred)})

     y_test         y_pred           MAE           MSE        R2
696  162859  163363.317310  15783.424382  3.861548e+08  0.857887
667  129973  128659.062416  15783.424382  3.861548e+08  0.857887
63   192309  177992.787685  15783.424382  3.861548e+08  0.857887
533  115959  121116.494155  15783.424382  3.861548e+08  0.857887
66   107429  110119.908985  15783.424382  3.861548e+08  0.857887
..      ...            ...           ...           ...       ...
589  171958  156651.863165  15783.424382  3.861548e+08  0.857887
798  108608   95946.470644  15783.424382  3.861548e+08  0.857887
744  180261  175375.995922  15783.424382  3.861548e+08  0.857887
513   88876  110250.141015  15783.424382  3.861548e+08  0.857887
670  214959  214158.847729  15783.424382  3.861548e+08  0.857887

[160 rows x 5 columns]